config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  devise_scope :user do
    root 'posts#index'
    # authenticated :user do
    #   root 'posts#index', as: :authenticated_root
    # end
    # unauthenticated do
    #   root 'devise/sessions#new', as: :unauthenticated_root
    # end
  end
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def username
    User.find(self.user_id).email
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  def username
    User.find(self.user_id).email
  end

  def comments_count
    self.comments.all.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?

    protected

    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :username, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :username, :email, :password, :current_password)}
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /comments or /comments.json
  def index
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new  
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to posts_path, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :post_id)
    end

    def get_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy]
  before_action :authenticate_user!, only: %i[create]
  
  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @comment = Comment.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :post, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="make-comment">
  
  <div class="comment-modal">
    <div class="container close-modal">
      <div id="close-comment-modal" class="close-btn"><p>X</p></div>
    </div>
    <div class="post-creator container">
      <div>
        <div class ="profile-image">
            <img src="" alt="">
        </div>
      </div>
      <div>
        <div class="post-details">
            <p class="username"><%= User.find(@post.user_id).email%></p>
            <p><%= @post.created_at %></p>
        </div>
        <div class="post-content">
            <p><%= @post.post%></p>
        </div>
      </div>
    </div>

    <div class="container comment-form">
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      
            <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="commenter">
          <div class ="profile-image">
            <img src="" alt="">
        </div>
          <%= form.text_area :comment, placeholder: "Write your comment"%>
        </div>
        <div>
          <%= form.hidden_field :user_id, value: current_user.id%>
        </div>
        <div class="action">
          <%= form.submit class: "btn btn-comment" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form',comment: @comment %>

app/views/comments/new.js.erb
comment = document.querySelector('#comment-modal');
while (comment.firstChild) {
    comment.removeChild(comment.lastChild);
}
comment.insertAdjacentHTML("beforeend", "<%= j (render "form")%>")
comment.style.display = "block"
closeBtn = document.getElementById('close-comment-modal');

closeBtn.onclick = function () {
    comment.style.display = "none"
}

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "navigation/navigation"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/navigation/_navigation.html.erb
<nav class="container nav-container">
    <div class="navigation">
        <div class="home">
            <%= link_to "Home", posts_path %>
        </div>

        <div class="nav-links">
            <%= link_to "Profile", "#" %>

            <% if user_signed_in?%>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                <% else %>
                <%= link_to "Log in", new_user_session_path, class: "btn"%>
            <% end %>
            
        </div>
    </div>
</nav>

app/views/posts/_comment.html.erb
<div class="post container">
    <div>
        <div class ="profile-image">
            <img src="" alt="">
        </div>
    </div>
    <div>
    
        <div class="post-details">
            <p class="username"><%= comment.username%></p> 
            <p><%= comment.created_at %></p>
        </div>
        <div class="post-content">
            <p><%= comment.comment%></p>
        </div>
        <div class="post-engagements">
            <div class="engagement">
                
                    <i class="fa fa-comments" aria-hidden="true"></i>
            
                <p>1</p>
            </div>
            <div class="engagement">
                <i class="fa fa-thumbs-up"></i>
                <p>1</p>
            </div>
        </div>
    </div>   
</div>

app/views/posts/_form.html.erb
<div>
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
  
        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.text_area :post%>
    </div>
  
  
    <div class="actions">
      <%= form.submit class: "btn"%>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post container" data-id = "<%= post.id %>" data-controller = "<%= controller.action_name %>">
    
    <% presenter = PostPresenter.new(post)%>
    <div>
        <div class ="profile-image">
            <img src="" alt="">
        </div>
    </div>
    <div>
        <% if user_signed_in? %>
        <div class="post-details">
            <p class="username"><%= presenter.username %></p> 
            <p><%= presenter.date_posted %></p>
        </div>
        <% end %>
        <div class="post-content">
            <p><%= post.post%></p>
        </div>
        <div class="post-engagements">
            <div class="engagement engage-comment">
                <%= link_to new_post_comment_path(post_id: post.id), remote: true do %>
                    <i class="fa fa-comments" aria-hidden="true"></i>
                <% end %>
                <p><%= presenter.comments_count %></p>
                
                
            </div>
            <div class="engagement like-post">
                <i class="fa fa-thumbs-up"></i>
                <p>1</p>
            </div>
            <% if user_signed_in? %>
                <% if post.user_id == current_user.id%>
                    <div class="engagement edit-post">
                        <%= link_to edit_post_path(id: post.id), local: true do%>
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        <% end %>
                    </div>
                    <div class="engagement delete-post">
                        <%= link_to post_path(post), data: {:confirm => 'Delete this post? '}, :method => :delete do %>
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        <% end %>
                    </div>    
                <% end %>
            <% end %>
        </div>
    </div>   
</div>

app/views/posts/edit.html.erb
<div class="container create-post">
    <div class="title-section">
        <h2>Edit Post</h2>
        <div class="draft">
            <p>Drafts</p>
            <p>0</p>
        </div>
    </div>

    <div class="form-area">
        <div class="textarea">
            <div class="settings">
                <p>B</p>
                <p>i</p>
                <p>l</p>
            </div>
            <%= render 'form', post: @post %>
        </div>
    </div>	
</div>

app/views/posts/index.html.erb
<div id="comment-modal">
    
</div>

<main class="home-page">
     
    <div id="home-pg-profile-section">
        <%= render "devise/profile"%>
    </div>
    <div id="posts">
        <%= render partial: "post", collection: @posts %>
    </div>
</main>





     

app/views/posts/new.html.erb
<div class="container create-post">
    <div class="title-section">
        <h2>Create a post</h2>
        <div class="draft">
            <p>Drafts</p>
            <p>0</p>
        </div>
    </div>

    <div class="form-area">
        <div class="textarea">
            <div class="settings">
                <p>B</p>
                <p>i</p>
                <p>l</p>
            </div>
            <%= render 'form', post: @post %>
        </div>
    </div>	
</div>

app/views/posts/show.html.erb
<div class="post-show-page">
  <div class="show-pg-post">
    <%= render "post",  post: @post %>
  </div>
  <div class="comment-section container">
    <%= render partial: "comment", collection: @comments%>
  </div>
</div>